# Fase de construcción con Node.js
FROM node:19-alpine AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de dependencias y realizar la instalación
COPY frontend/package*.json ./
COPY frontend/package-lock.json ./
RUN npm install

# Copiar el código fuente de la aplicación
COPY frontend/ ./
RUN npm run build

# Fase de producción con Nginx
FROM nginx:alpine

# Copiar los archivos construidos desde la fase anterior
COPY --from=build /app/build /usr/share/nginx/html

# Copiar la configuración personalizada de nginx
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 80

# Ejecutar nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
