# Usar la imagen base de Node.js
FROM node:19-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de dependencias del backend
COPY backend/package*.json ./

# Instalar las dependencias necesarias
RUN npm install morgan
RUN npm install -g pnpm
RUN npm install

# Copiar el código fuente al contenedor
COPY backend/src/ ./src/
COPY backend/src/config.js ./src/

# Exponer el puerto en el que el backend escucha
EXPOSE 4000

# Ajustar el HEALTHCHECK para monitorear la salud del contenedor
HEALTHCHECK --interval=10s --timeout=5s --retries=3 CMD wget --no-verbose --tries=1 --spider http://localhost:4000/api/notes || exit 1

# Comando para iniciar la aplicación
CMD ["node", "src/index.js"]
